# SITE CONFIGURATION
title: Jaime's Design Blog # your site title
author: Jaime Echevarria Corrales # You
description: > # Meta description of Homepage
  Design Blog by Jaime Echevarria Corrales.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jaimeechevarria.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Jaime Echevarria Corrales
  links:
    - https://www.linkedin.com/in/jaimeechevarria
    - https://github.com/jaimeechevarria

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'CV', link: '/CV'}

tagline: >
  Jaime Echevarría Corrales

hero_img: general/hero_img.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/general/hero_img.jpg

email: jaime99echevarria@gmail.com # email for form submission

#twitter_username: jaimeechevarria # replace with your_twitter_username or comment to remove link from footer
github_username:  jaimeechevarria # replace with your_github_username or comment to remove link from footer
linkedin_username: jaimeechevarria
#instagram_username: jaimeechevarria # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: jaimeechevarria-github-io # to enable comments replace with your_disqus_shortname

#google_tag_manager: GTM-W7LBXHH # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
